### ISSUE TITLE
Profile loading is too slow on pay screen

### ISSUE THREAD

**Issue by bumi** [getAlby/pos#14]
For me the profile loading is quite slow and only after 1-2 seconds the name and the avatar is shown.

**Comment by rolznz** [comment]
This is also the case for the items list and could be fixed by caching the events to localStorage.

Currently I used nostr-hooks and created an [issue](https://github.com/sepehr-safari/nostr-hooks/issues/14).

I see ndk has support for clientside caching with IndexDB: https://github.com/nostr-dev-kit/ndk/tree/master/ndk

**Comment by sepehr-safari** [comment]
I've sent a PR and replaced nostr-hooks with ndk using IndexedDB caching mechanism. please make sure to review and test it before merging. I'm open to fix any possible issue.

**Comment by rolznz** [comment]
fixed in https://github.com/getAlby/pos/pull/21
